### ISSUE TITLE
add 'mircosoft Edge dev' and 'google chromium'

### ISSUE THREAD

**Issue by jide23work** [zeitlings/alfred-set-default-browser#1]
sir, ask something for about [Alfred-set-default-browser],can u add 'mircosoft Edge dev' and 'google chromium' tools for it

**Comment by zeitlings** [comment]
Hey, have you tried setting the bundle identifiers for those apps (or just their names for testing purposes) in the *List Filter* yourself? The workflow should pick up on them.

![add1](https://user-images.githubusercontent.com/25689591/230386289-c8f038ab-c40a-4d19-894f-79eed6a598f2.jpg)
![add2](https://user-images.githubusercontent.com/25689591/230386305-c10de078-80bb-4920-9314-5b8cdf9b4f6e.jpg)
