### ISSUE TITLE
Does not function as described.

### ISSUE THREAD

**Issue by alpha114111** [zeitlings/alfred-set-default-browser#3]
Macos 13.5.2 (M2) doesn't throw an error or success dialogue box, I just hit return in alfred and nothing happens.

**Comment by zeitlings** [comment]
If Alfred's debugger (cmd+D) really does not display any errors or other information, I cannot help you with the information you have provided.

**Comment by alpha114111** [comment]
Apologies, I'm a total noob. I had  `` xcrun: error: invalid active developer path `` in my debug output. Installing the xcode command line tools (``xcode-select --install`` in Terminal) fixed it. Thanks for pointing me toward the debugger.
